In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
!nvidia-smi

Mon Mar 24 20:02:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Tensors


In [3]:
# Scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [12]:
# Get tensor back as python int
scalar_item = scalar.item()
scalar_item, scalar
# scalar_item.ndim # doesn't work

(7, tensor(7))

In [13]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [17]:
vector.shape
# vector.item # doesn't work as vector with more than one item cant be converted to scaler

torch.Size([2])

In [18]:
# Matrix
Matrix = torch.tensor([[7,8],
                      [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
Matrix.ndim

2

In [22]:
Matrix.shape

torch.Size([2, 2])

In [25]:
# Tensor
Tensor = torch.tensor([[[[1,2,3],
                        [3,4,6],
                        [4,7,8]]],[[[2,3,4],
                                   [2,5,6],
                                   [4,6,7]]]])
Tensor

tensor([[[[1, 2, 3],
          [3, 4, 6],
          [4, 7, 8]]],


        [[[2, 3, 4],
          [2, 5, 6],
          [4, 6, 7]]]])

In [26]:
Tensor.ndim

4

In [27]:
Tensor.shape

torch.Size([2, 1, 3, 3])

In [28]:
Tensor[0] # dim. 1

tensor([[[1, 2, 3],
         [3, 4, 6],
         [4, 7, 8]]])

In [29]:
Tensor[0][0] # dim. 2

tensor([[1, 2, 3],
        [3, 4, 6],
        [4, 7, 8]])

In [30]:
Tensor[0][0][0] # dim. 3

tensor([1, 2, 3])

In [31]:
Tensor[0][0][0][0] # dim. 4 ,result (1)

tensor(1)

In [35]:
Tensor[1][0][1][1] # dim. 4 ,result (5)

tensor(5)

In [32]:
Tensor[0][0][2][2] #8

tensor(8)

### Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [36]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7771, 0.7066, 0.7447, 0.0448],
        [0.0134, 0.9343, 0.0821, 0.2058],
        [0.6119, 0.5517, 0.7515, 0.3520]])

In [37]:
random_tensor.ndim

2

In [41]:
random_tensor.shape

torch.Size([3, 4])

In [42]:
# Create a random tensor with similar shape to an image tensor
random_imge_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_imge_size_tensor.shape, random_imge_size_tensor.ndim , # random_imge_size_tensor

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [43]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
# Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
ones.dtype # Default type it starts as torch.float32

torch.float32

### Creat a range of tensors and tensors-like


In [47]:
one_to_ten=torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# Creating tensor like zeros_like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big erros you'll run into with pytorch & Deep learning in general

1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on the right device

In [50]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # "cpu","cuda" what device is your tensor on
                               requires_grad=False) # Tracking gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# change type of tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([1,3,3], dtype=torch.int32)
int_32_tensor

tensor([1, 3, 3], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 3., 18., 27.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor can use `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensor not on the right device - `tensor.device`

In [51]:
some_tensor = torch.rand(size=(3,4),
                         dtype=torch.float16,
                         device="cpu")
some_tensor

tensor([[0.9546, 0.8696, 0.6167, 0.3140],
        [0.2256, 0.7847, 0.4043, 0.1689],
        [0.5684, 0.7246, 0.0566, 0.8477]], dtype=torch.float16)

In [52]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}, {some_tensor.size()} ")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9546, 0.8696, 0.6167, 0.3140],
        [0.2256, 0.7847, 0.4043, 0.1689],
        [0.5684, 0.7246, 0.0566, 0.8477]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4]), torch.Size([3, 4]) 
Device tensor is on: cpu


### Manipulating tensor (Tensor operations)

* addition
* substraction
* Multiplication (element-wise)
* Divison
* Matrix multiplication

In [53]:
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [54]:
tensor * 10

tensor([10, 20, 30])

In [55]:
tensor - 10

tensor([-9, -8, -7])

In [56]:
tensor / 1

tensor([1., 2., 3.])

In [57]:
# Pytorch in-built function
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [58]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [59]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix multiplication

Two ways:
- Element-wise multiplication
- Matrix multiplication (dot product)

In [60]:
# Element wise
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [61]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 1.75 ms


In [63]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 292 µs, sys: 45 µs, total: 337 µs
Wall time: 274 µs


tensor(14)

### Matrix multiplication

Two rules
1. The inner dimensions must match:
  `(3, 2) @ (3, 2)` won't work
  `(2, 3) @ (3, 2)` will work
 2. The resulting matrix has the shape of the outer dimensions
 `(2, 3) @ (3, 2)` -> `(2,2)`


In [64]:
torch.matmul(torch.rand(3,10), torch.rand(10,3)).size()

torch.Size([3, 3])

In [65]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)
tensor_A.shape, tensor_B.shape

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
# To fix out tensor shape issues we can maniplulate the shape one of the tensors using transpose
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding min , max , mean , sum , etc (tensor aggregation)

In [69]:
x = torch.arange(0, 100, 10) # Exclusive
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
x.dtype

torch.int64

In [71]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [72]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [73]:
# torch.mean() requires tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [74]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Find the positional min and max (the position of the max and the min value)
also know as `argmin() ` and `argmax()`


In [75]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
x.argmin()

tensor(0)

In [77]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor of a defined shape
* View - Return a view of an input tensor of a certain shape and keep the same memory
* Stacking - combine multiple tensores if each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [78]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [79]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [80]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [82]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [83]:
# Squeez
x_reshaped.shape, x_reshaped.squeeze().shape, x_reshaped, x_reshaped.squeeze()

(torch.Size([1, 9]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimesnions x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [85]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimesnions x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [86]:
# Permute - rearranges the dimensions of a target tensor in a specified order
x = torch.randn(2, 3, 5)
x.size(), torch.permute(x, (2, 0, 1)).size()

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [87]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [89]:
x_original[0,0,0] = 728218
x_permuted[0,0,0] # share the same memory

tensor(728218.)

## Indexing
Indexing with pytorch is similar to indexing with numpy

In [90]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
x[0,1,1] # 5

tensor(5)

In [93]:
x[0,2,2] # 9

tensor(9)

In [94]:
x = torch.arange(1, 19).reshape(1,6,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([1, 6, 3]))

In [95]:
x[0,5,2]

tensor(18)

In [96]:
# use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [97]:
x[:,:,2]

tensor([[ 3,  6,  9, 12, 15, 18]])

In [98]:
x[:,1,:]

tensor([[4, 5, 6]])

In [99]:
x[:,1,2]

tensor([6])

In [100]:
# all values of the 0 dimension but only the 1 index of 1st and 2nd
x[:,1,1]

tensor([5])

In [101]:
x[0,0,:]

tensor([1, 2, 3])

In [102]:
x[:,5,2]

tensor([18])

## Pytorch tensors & numpy

* Data in numpy -> want in pytorch tensor `torch.from_numpy(ndarray)`
* Pytorch tensor -> numpy : `torch.Tensor.numpy()`

In [105]:
# Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [106]:
array.dtype

dtype('float64')

In [107]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [108]:
tensor=torch.from_numpy(array).type(torch.float32) # pytorch reflects numpy's default datatype 'float64' unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [109]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [110]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:
tensor = tensor  +1
tensor, numpy_tensor # they don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducebility (trying to take random out of random)

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

### To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

https://pytorch.org/docs/stable/notes/randomness.html

In [112]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5552, 0.4580, 0.8390, 0.0990],
        [0.4418, 0.3960, 0.3016, 0.0554],
        [0.5895, 0.2436, 0.5328, 0.9429]])

Tensor B:
tensor([[0.0822, 0.5978, 0.8509, 0.4478],
        [0.2556, 0.5163, 0.9207, 0.5653],
        [0.2930, 0.9982, 0.5747, 0.9041]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [113]:
# Random but reproducible tensors

# Set random seed
random_seed = 42

torch.manual_seed(seed=random_seed)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(seed=random_seed)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (for faster computations)

## 1. Getting a GPU

1. Google collab or kaggle
2. Using your own gpu , guide: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS ,Azure

for 2,3 pytorch + gpu (cuda) require a little bit of setting up , https://pytorch.org/get-started/locally/

In [114]:
!nvidia-smi

Mon Mar 24 20:41:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2.Check for GPU access with pytorch

In [115]:
# Check for gput access with pytorch
torch.cuda.is_available()

True

#### Device agnostic code
Best practice is to Setup device agnostic code

https://pytorch.org/docs/stable/notes/cuda.html

In [116]:
# Best practice
# Setup device agnostic code
# If we got GPU , code will use it
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
device

Using device: cuda


'cuda'

In [117]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU
For faster computation

In [118]:
# Create a tensor (default on the cpu)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [119]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU (numpy work on cpu)

In [120]:
tensor_on_gpu.cpu().numpy()


array([1, 2, 3])

In [121]:
# To fix the GPU tensor with numpy issue, we can first set it to the GPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [122]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb