# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.8188, 0.1658, 0.5077, 0.5187, 0.0494, 0.7768, 0.3713],
        [0.5824, 0.2821, 0.8716, 0.7361, 0.3695, 0.5755, 0.6096],
        [0.7536, 0.4139, 0.4152, 0.4172, 0.8767, 0.0202, 0.1100],
        [0.8954, 0.8024, 0.0826, 0.2392, 0.6468, 0.5441, 0.9017],
        [0.7982, 0.2990, 0.0480, 0.6808, 0.8056, 0.2638, 0.5624],
        [0.1809, 0.7517, 0.0410, 0.8335, 0.2367, 0.2683, 0.1064],
        [0.9466, 0.8528, 0.2580, 0.2725, 0.8761, 0.7050, 0.9938]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
rand_tensor2 = torch.rand(1,7)

# Perform matrix multiplication
# mat_mul = rand_tensor@rand_tensor.T # one way using @
# rand_tensor2_transposed =  rand_tensor2.T
mat_mul = torch.matmul(rand_tensor, rand_tensor2.T)
mat_mul

tensor([[2.0174],
        [2.2610],
        [1.5898],
        [2.1675],
        [1.8616],
        [1.1791],
        [2.6436]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
rand_tensor = torch.rand(7,7)
rand_tensor2 = torch.rand(1,7)


# Matrix multiply tensors
mat_mul = torch.matmul(rand_tensor, rand_tensor2.T)
mat_mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(42)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(42)
rand1 = torch.rand(2,3)
rand2 = torch.rand(2,3)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU

rand1_gpu =  rand1.to(device='cuda')
rand2_gpu =  rand2.to(device='cuda')

rand1 , rand2, rand1_gpu, rand2_gpu

(tensor([[0.0340, 0.9442, 0.8802],
         [0.0012, 0.5936, 0.4158]]),
 tensor([[0.4177, 0.2711, 0.6923],
         [0.2038, 0.6833, 0.7529]]),
 tensor([[0.0340, 0.9442, 0.8802],
         [0.0012, 0.5936, 0.4158]], device='cuda:0'),
 tensor([[0.4177, 0.2711, 0.6923],
         [0.2038, 0.6833, 0.7529]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
mat_mul_tensor = torch.matmul(rand1_gpu, rand2_gpu.T)
mat_mul_tensor ,mat_mul_tensor.shape

(tensor([[0.8795, 1.3148],
         [0.4493, 0.7189]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = mat_mul_tensor.max()
# Find min
min = mat_mul_tensor.min()

max, min

(tensor(1.3148, device='cuda:0'), tensor(0.4493, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = mat_mul_tensor.argmax()
# Find arg min
min_index = mat_mul_tensor.argmin()
max_index ,min_index

(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t1 = torch.rand(1,1,1,10)


# Remove single dimensions
t2 = t1.squeeze()

# Print out tensors and their shapes
t1, t1.shape, t2, t2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))